---
- hosts: rhel10-base
  become: true
  collections:
    - ch_collections.base
  pre_tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"
      
    # - name: Updating System Packages Before Ansible Run
    #   package:
    #     name: "*"
    #     state: latest
    - name: CodeReady repo check
      block:
        - name: Check CodeReady repo exists but disabled
          ansible.builtin.stat:
            path: /etc/yum.repos.d/redhat-rhui.repo.disabled
          register: repo_disabled
        - name: Move redhat-rhui repo file to enabled
          ansible.builtin.copy:
            src: /etc/yum.repos.d/redhat-rhui.repo.disabled
            dest: /etc/yum.repos.d/redhat-rhui.repo
            remote_src: yes
          when: repo_disabled.stat.exists
        - name: show contents of repo folder
          find:
            paths: /etc/yum.repos.d/
        - name: Check CodeReady repo exists and enabled
          ansible.builtin.stat:
            path: /etc/yum.repos.d/redhat-rhui.repo
          register: repo_exists
        - name: Enable CodeReady repo on RHEL10
          ini_file:
            dest: /etc/yum.repos.d/redhat-rhui.repo
            section: codeready-builder-for-rhel-10-rhui-rpms
            option: enabled
            value: "1"
          when: repo_exists.stat.exists
      when: (ansible_os_family == 'RedHat') and (ansible_distribution_major_version | int == 10)

    - name: Set timezone to Europe/London
      community.general.timezone:
        name: Europe/London

    - name: Install Amazon SSM agent
      ansible.builtin.command: dnf install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm --nogpgcheck
    - name: Enable Amazon SSM agent
      ansible.builtin.command: systemctl enable amazon-ssm-agent
    - name: Enable Amazon SSM agent
      ansible.builtin.command: systemctl start amazon-ssm-agent

    - name: Set root password.
      shell: openssl rand -base64 200 | tr -d '\n' | passwd --stdin root

  roles:
    - geerlingguy.repo-epel
    - ch_collections.base.os_package_control
    - RHEL10-CIS
    - companieshouse.security.clamav_ng
    - companieshouse.infrastructure.linux_cloudwatch_agent_config
    - ch_collections.base.cron_control
    - ch_collections.security_banner.banner
    - crypto_policy
    - disable_mounting
    - journald
    - password_policy
    - ptrace
    - session_timeout
    - ssh_hardening
    - umask
    - user_init
    - verify_audit_tools
    - pam
    - network_security
    - aws-cli
    - post-build-fixes
    - companieshouse.security.security_scans